# Generated by Django 5.2 on 2026-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_checklist_task_alter_checklistitem_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
